name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjAxZDkxZDctMWNmYS00YTNkLTkwYmEtMmEwODc4ZTA1NDk0IiwidGVuYW50X2lkIjoiMjQzZGMzZGE0MWVhZDllMWExZTExMDY2ZDM2NGM4NTRkZmZmYjliMGM1ZWY4Y2JlYjUzZDA0ZGJlNmRlNjY0OCIsImludGVybmFsX3NlY3JldCI6IjJiYjEzYmVhLTgxN2UtNDg5MS1iZDdiLTQyNTljNmJlNDdiNCJ9.sco-nTqnqRNpvTOs2m8HB6LXNlksS4n4HHpEFpxjQIM"
JWT_SECRET="Mypassword"
